<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class DeliverablesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('deliverables')->insert([

            // SIESTA 1 of 2
            [
                'project_id' => 2,
                'milestone_id' => 1,
                'position' => 0,
                'description' => 'Contract signing',
                'status' => 'COMPLETE',
                'datetime_started' => Carbon::create(2023, 6, 15, 6, 30, 0),
                'datetime_completed' => Carbon::create(2023, 6, 16, 6, 30, 0),
            ],
            [
                'project_id' => 2,
                'milestone_id' => 2,
                'position' => 0,
                'description' => 'Mooboard',
                'status' => 'COMPLETE',
                'datetime_started' => Carbon::create(2023, 6, 15, 6, 30, 0),
                'datetime_completed' => Carbon::create(2023, 6, 16, 6, 30, 0),
            ],
            [
                'project_id' => 2,
                'milestone_id' => 2,
                'position' => 1,
                'description' => 'Study Concepts and Logo options. Lorem ipsum dolor sit amet.',
                'status' => 'COMPLETE',
                'datetime_started' => Carbon::create(2023, 6, 18, 6, 30, 0),
                'datetime_completed' => Carbon::create(2023, 6, 20, 6, 30, 0),
            ],
            [
                'project_id' => 2,
                'milestone_id' => 2,
                'position' => 2,
                'description' => 'Editing incomplete deliverable. Ongoing deliverable with images. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,',
                'status' => 'COMPLETE',
                'datetime_started' => Carbon::create(2023, 6, 18, 6, 30, 0),
                'datetime_completed' => Carbon::create(2023, 6, 20, 6, 30, 0),
            ],
            [
                'project_id' => 2,
                'milestone_id' => 2,
                'position' => 3,
                'description' => 'Cancelled deliverable',
                'status' => 'COMPLETE',
                'datetime_started' => Carbon::create(2023, 6, 18, 6, 30, 0),
                'datetime_completed' => Carbon::create(2023, 6, 20, 6, 30, 0),
            ],
            [
                'project_id' => 2,
                'milestone_id' => 3,
                'position' => 0,
                'description' => 'Wireframes',
                'status' => 'INCOMPLETE',
                'datetime_started' => Carbon::create(2023, 6, 18, 6, 30, 0),
                'datetime_completed' => Carbon::create(2023, 6, 20, 6, 30, 0),
            ],
            [
                'project_id' => 2,
                'milestone_id' => 3,
                'position' => 1,
                'description' => 'User interface and component mockups',
                'status' => 'COMPLETE',
                'datetime_started' => Carbon::create(2023, 6, 18, 6, 30, 0),
                'datetime_completed' => Carbon::create(2023, 6, 20, 6, 30, 0),
            ],
            [
                'project_id' => 2,
                'milestone_id' => 3,
                'position' => 2,
                'description' => 'Protoype',
                'status' => 'INCOMPLETE',
                'datetime_started' => Carbon::create(2023, 6, 18, 6, 30, 0),
                'datetime_completed' => Carbon::create(2023, 6, 20, 6, 30, 0),
            ],
            [
                'project_id' => 2,
                'milestone_id' => 4,
                'position' => 0,
                'description' => 'Market, competition, and demography research',
                'status' => 'INCOMPLETE',
                'datetime_started' => Carbon::create(2023, 6, 18, 6, 30, 0),
                'datetime_completed' => Carbon::create(2023, 6, 20, 6, 30, 0),
            ],
            [
                'project_id' => 2,
                'milestone_id' => 4,
                'position' => 1,
                'description' => 'Setup of marketing channels: Facebook, LinkedIn, Instagram, Tiktok,',
                'status' => 'INCOMPLETE',
                'datetime_started' => Carbon::create(2023, 6, 18, 6, 30, 0),
                'datetime_completed' => Carbon::create(2023, 6, 20, 6, 30, 0),
            ],
            [
                'project_id' => 2,
                'milestone_id' => 4,
                'position' => 2,
                'description' => 'Google analytics setup',
                'status' => 'INCOMPLETE',
                'datetime_started' => Carbon::create(2023, 6, 18, 6, 30, 0),
                'datetime_completed' => Carbon::create(2023, 6, 20, 6, 30, 0),
            ],

            // WAVEKO

            [
                'project_id' => 1,
                'milestone_id' => 5,
                'position' => 0,
                'description' => 'Survey and Planning',
                'status' => 'COMPLETE',
                'datetime_started' => Carbon::create(2023, 6, 15, 6, 30, 0),
                'datetime_completed' => Carbon::create(2023, 6, 16, 6, 30, 0),
            ],
            [
                'project_id' => 1,
                'milestone_id' => 5,
                'position' => 1,
                'description' => 'Approval',
                'status' => 'COMPLETE',
                'datetime_started' => Carbon::create(2023, 6, 15, 6, 30, 0),
                'datetime_completed' => Carbon::create(2023, 6, 16, 6, 30, 0),
            ],
            [
                'project_id' => 1,
                'milestone_id' => 5,
                'position' => 2,
                'description' => 'Backend',
                'status' => 'COMPLETE',
                'datetime_started' => Carbon::create(2023, 6, 15, 6, 30, 0),
                'datetime_completed' => Carbon::create(2023, 6, 16, 6, 30, 0),
            ],
            [
                'project_id' => 1,
                'milestone_id' => 6,
                'position' => 0,
                'description' => 'Brief + Project Plan',
                'status' => 'COMPLETE',
                'datetime_started' => Carbon::create(2023, 6, 15, 6, 30, 0),
                'datetime_completed' => Carbon::create(2023, 6, 16, 6, 30, 0),
            ],
            [
                'project_id' => 1,
                'milestone_id' => 6,
                'position' => 1,
                'description' => 'Study Concepts, Branding',
                'status' => 'INCOMPLETE',
                'datetime_started' => Carbon::create(2023, 6, 18, 6, 30, 0),
                'datetime_completed' => Carbon::create(2023, 6, 20, 6, 30, 0),
            ],
            [
                'project_id' => 1,
                'milestone_id' => 6,
                'position' => 2,
                'description' => 'SEO Strategy',
                'status' => 'INCOMPLETE',
                'datetime_started' => Carbon::create(2023, 6, 18, 6, 30, 0),
                'datetime_completed' => Carbon::create(2023, 6, 20, 6, 30, 0),
            ],
            [
                'project_id' => 1,
                'milestone_id' => 6,
                'position' => 3,
                'description' => 'Google Ads',
                'status' => 'COMPLETE',
                'datetime_started' => Carbon::create(2023, 6, 18, 6, 30, 0),
                'datetime_completed' => Carbon::create(2023, 6, 20, 6, 30, 0),
            ],
            [
                'project_id' => 1,
                'milestone_id' => 6,
                'position' => 3,
                'description' => 'Social Media Ads',
                'status' => 'INCOMPLETE',
                'datetime_started' => Carbon::create(2023, 6, 18, 6, 30, 0),
                'datetime_completed' => Carbon::create(2023, 6, 20, 6, 30, 0),
            ],
            [
                'project_id' => 1,
                'milestone_id' => 7,
                'position' => 0,
                'description' => 'Packaging',
                'status' => 'INCOMPLETE',
                'datetime_started' => Carbon::create(2023, 6, 18, 6, 30, 0),
                'datetime_completed' => Carbon::create(2023, 6, 20, 6, 30, 0),
            ],
            [
                'project_id' => 1,
                'milestone_id' => 7,
                'position' => 1,
                'description' => 'Product Distribution',
                'status' => 'INCOMPLETE',
                'datetime_started' => Carbon::create(2023, 6, 18, 6, 30, 0),
                'datetime_completed' => Carbon::create(2023, 6, 20, 6, 30, 0),
            ],

            // TRUCKFLOW

            [
                'project_id' => 5,
                'milestone_id' => 8 ,
                'position' => 0,
                'description' => 'Define requirements and objectives',
                'status' => 'COMPLETE',
                'datetime_started' => Carbon::create(2023, 6, 18, 6, 30, 0),
                'datetime_completed' => Carbon::create(2023, 6, 20, 6, 30, 0),
            ],
            [
                'project_id' => 5,
                'milestone_id' => 8 ,
                'position' => 1,
                'description' => 'Identify key features such as order management, route optimization, real-time tracking, reporting, user management, and more.',
                'status' => 'COMPLETE',
                'datetime_started' => Carbon::create(2023, 6, 18, 6, 30, 0),
                'datetime_completed' => Carbon::create(2023, 6, 20, 6, 30, 0),
            ],
            [
                'project_id' => 5,
                'milestone_id' => 8 ,
                'position' => 2,
                'description' => 'Consider scalability, security, and user experience.',
                'status' => 'COMPLETE',
                'datetime_started' => Carbon::create(2023, 6, 18, 6, 30, 0),
                'datetime_completed' => Carbon::create(2023, 6, 20, 6, 30, 0),
            ],
            [
                'project_id' => 5,
                'milestone_id' => 9 ,
                'position' => 0,
                'description' => 'Consider scalability, security, and user experience.',
                'status' => 'COMPLETE',
                'datetime_started' => Carbon::create(2023, 6, 18, 6, 30, 0),
                'datetime_completed' => Carbon::create(2023, 6, 20, 6, 30, 0),
            ],
            [
                'project_id' => 5,
                'milestone_id' => 9 ,
                'position' => 1,
                'description' => 'Database design',
                'status' => 'COMPLETE',
                'datetime_started' => Carbon::create(2023, 6, 18, 6, 30, 0),
                'datetime_completed' => Carbon::create(2023, 6, 20, 6, 30, 0),
            ],
            [
                'project_id' => 5,
                'milestone_id' => 9 ,
                'position' => 2,
                'description' => 'Design the database schema to store information about orders, drivers, vehicles, routes, and other relevant data. Implement a relational database (e.g., MySQL, PostgreSQL) for data storage.',
                'status' => 'COMPLETE',
                'datetime_started' => Carbon::create(2023, 6, 18, 6, 30, 0),
                'datetime_completed' => Carbon::create(2023, 6, 20, 6, 30, 0),
            ],
            [
                'project_id' => 5,
                'milestone_id' => 9 ,
                'position' => 3,
                'description' => 'Implement user authentication and authorization mechanisms',
                'status' => 'COMPLETE',
                'datetime_started' => Carbon::create(2023, 6, 18, 6, 30, 0),
                'datetime_completed' => Carbon::create(2023, 6, 20, 6, 30, 0),
            ],
            [
                'project_id' => 5,
                'milestone_id' => 9 ,
                'position' => 4,
                'description' => 'Implement a system for managing cargo orders.',
                'status' => 'COMPLETE',
                'datetime_started' => Carbon::create(2023, 6, 18, 6, 30, 0),
                'datetime_completed' => Carbon::create(2023, 6, 20, 6, 30, 0),
            ],
            [
                'project_id' => 5,
                'milestone_id' => 10 ,
                'position' => 0,
                'description' => 'Allow users to place, modify, and track orders',
                'status' => 'COMPLETE',
                'datetime_started' => Carbon::create(2023, 6, 18, 6, 30, 0),
                'datetime_completed' => Carbon::create(2023, 6, 20, 6, 30, 0),
            ],
            [
                'project_id' => 5,
                'milestone_id' => 10 ,
                'position' => 1,
                'description' => 'Route optimization',
                'status' => 'COMPLETE',
                'datetime_started' => Carbon::create(2023, 6, 18, 6, 30, 0),
                'datetime_completed' => Carbon::create(2023, 6, 20, 6, 30, 0),
            ],
            [
                'project_id' => 5,
                'milestone_id' => 10 ,
                'position' => 2,
                'description' => 'Provide a user interface for customers and administrators to track shipments',
                'status' => 'COMPLETE',
                'datetime_started' => Carbon::create(2023, 6, 18, 6, 30, 0),
                'datetime_completed' => Carbon::create(2023, 6, 20, 6, 30, 0),
            ],

            // SIESTA 2 of 2
            [
                'project_id' => 2,
                'milestone_id' => 11,
                'position' => 0,
                'description' => 'All hands meeting',
                'status' => 'INCOMPLETE',
                'datetime_started' => Carbon::create(2023, 6, 18, 6, 30, 0),
                'datetime_completed' => null,
            ],
        ]);
    }
}
